"""
Visualization Script for Telco Churn Project
Reads JSON artifacts generated by the training script and produces
report-ready plots and tables in an 'telco_churn_output' folder.
"""

import json
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Define file paths
OUTPUT_DIR = "telco_churn_output"

GRADIENT_FILE = os.path.join(OUTPUT_DIR, "keras_gradients.json")
LEADERBOARD_FILE = os.path.join(OUTPUT_DIR, "model_leaderboard_telco.json")
KERAS_HISTORY_FILE = os.path.join(OUTPUT_DIR, "keras_history.csv")

def load_data():
    """Loads gradient and leaderboard data from JSON files."""
    with open(GRADIENT_FILE, "r") as f:
        gradients = json.load(f)
    
    with open(LEADERBOARD_FILE, "r") as f:
        leaderboard = json.load(f)

    with open(KERAS_HISTORY_FILE, "r") as f:
        history = pd.read_csv(f)
        
    return gradients, leaderboard, history

def setup_directories():
    """Creates the output directory if it doesn't exist."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        print(f"Created directory: {OUTPUT_DIR}")

def plot_gradients(gradients):
    """
    Plots gradient values over epochs.
    """
    # extract data for plotting
    epochs = [entry['epoch'] + 1 for entry in gradients] 
    means = [entry['grad_abs_mean'] for entry in gradients]
    maxs = [entry['grad_abs_max'] for entry in gradients]

    plt.figure(figsize=(10, 6))
    
    # Plot Mean and Max
    sns.lineplot(x=epochs, y=means, label='Mean Gradient (Abs)', marker='o', color='blue')
    sns.lineplot(x=epochs, y=maxs, label='Max Gradient (Abs)', marker='x', linestyle='--', color='red', alpha=0.6)

    # Log Scale Plot
    plt.title("Gradient Stability Analysis Over Epochs (Log Scale)")
    plt.xlabel("Epoch")
    plt.ylabel("Gradient Magnitude (Log Scale)")
    plt.yscale('log') # Log scale is critical for seeing vanishing gradients
    plt.grid(True, which="both", ls="-", alpha=0.2)
    plt.legend()
    
    save_path = os.path.join(OUTPUT_DIR, "gradient_stability_log_scale.png")
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"Saved Plot: {save_path}")
    plt.show()
    plt.close()

def plot_keras_history(history):
    """
    Plots Keras training history (Loss + Metrics) from CSV file.
    """
    
    # Create a figure with two subplots (1 row, 2 columns)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
    
    epochs = history.index + 1
    
    # LOSS
    sns.lineplot(x=epochs, y=history['loss'], label='Train Loss', ax=ax1, marker='o', color='blue')
    if 'val_loss' in history.columns:
        sns.lineplot(x=epochs, y=history['val_loss'], label='Val Loss', ax=ax1, marker='x', linestyle='--', color='orange')
    
    ax1.set_title("Model Loss")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Loss")
    ax1.grid(True, alpha=0.3)
    ax1.legend()

    # AUC
    # Automatically check if we tracked 'accuracy' or 'auc'
    metric = 'auc'
    val_metric = 'val_auc'
    title = "Model AUC"
        
    sns.lineplot(x=epochs, y=history[metric], label=f'Train {metric.upper()}', ax=ax2, marker='o', color='green')
    if val_metric in history.columns:
        sns.lineplot(x=epochs, y=history[val_metric], label=f'Val {metric.upper()}', ax=ax2, marker='x', linestyle='--', color='red')
    
    ax2.set_title(title)
    ax2.set_xlabel("Epoch")
    ax2.set_ylabel(metric.upper())
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    
    # Save the combined plot
    save_path = os.path.join(OUTPUT_DIR, "keras_training_history.png")
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"Saved Plot: {save_path}")
    plt.show()
    plt.close()

def plot_leaderboard(leaderboard):
    """
    Creates a horizontal bar chart comparing AUC scores across all models.
    """
    df = pd.DataFrame(leaderboard)
    
    plt.figure(figsize=(10, 6))
    
    # Create horizontal bar plot
    ax = sns.barplot(
        data=df, 
        x='auc', 
        y='name', 
        hue='type', 
        palette='viridis',
        orient='h'
    )
    
    # Add text labels on bars
    for i in ax.containers:
        ax.bar_label(i, fmt='%.4f', padding=3)

    plt.title("Model Performance Comparison (Validation AUC)")
    plt.xlabel("AUC Score")
    plt.ylabel("Model Name")
    plt.xlim(0.7, 0.9) # Adjust this zoom if your scores are different
    plt.grid(True, axis='x', alpha=0.3)
    
    save_path = os.path.join(OUTPUT_DIR, "model_leaderboard_auc.png")
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"Saved Plot: {save_path}")
    plt.show()
    plt.close()

def save_comparison_table(leaderboard):
    """
    Generates a clean CSV table for the report.
    """
    df = pd.DataFrame(leaderboard)
    
    # Select and rename columns for clarity
    cols_to_keep = ["name", "type", "auc", "accuracy", "grad_abs_mean"]
    # Filter for columns that actually exist
    existing_cols = [c for c in cols_to_keep if c in df.columns]
    
    clean_table = df[existing_cols].sort_values(by="auc", ascending=False)
    
    # Save to CSV (easy to copy-paste into Word/Docs)
    csv_path = os.path.join(OUTPUT_DIR, "model_comparison_table.csv")
    clean_table.to_csv(csv_path, index=False)
    print(f"Saved Table: {csv_path}")
    
    # Also print to console for quick verification
    print("\nFinal Comparison Table")
    print(clean_table.to_string(index=False))


def main():
    
    setup_directories()
    
    # Load Data
    gradients, leaderboard, history = load_data()
    if gradients is None:
        return

    # Generate Outputs
    plot_gradients(gradients)
    plot_leaderboard(leaderboard)
    save_comparison_table(leaderboard)
    plot_keras_history(history)
    
    print("\nAll Visualizations Complete")
    print(f"Check the '{OUTPUT_DIR}' folder for your images and CSV.")

if __name__ == "__main__":
    main()